export const GET_BUYERS = 'GET_BUYERS'
export const CREATE_BUYER = 'CREATE_BUYER'
export const UPDATE_BUYER = 'UPDATE_BUYER'
export const ERROR_BUYER = 'ERROR_BUYER'
export const VALIDATE_RUC = 'VALIDATE_RUC'
export const REPORT_USER = 'REPORT_USER'
export const BLOCK_USER = 'BLOCK_USER'